CREATE DATABASE QuanLyHoaDon
GO
USE QuanLyHoaDon
GO
CREATE TABLE KHACHHANG (
	MAKH VARCHAR(8) PRIMARY KEY,
	HO NVARCHAR(8),
	TEN NVARCHAR(20),
	NGSINH DATE,
	SONHA NVARCHAR(20),
	DUONG NVARCHAR(20),
	PHUONG NVARCHAR(20),
	QUAN NVARCHAR(20),
	TPHO NVARCHAR(20)
)
GO
CREATE TABLE HOADON (
	MAHD VARCHAR(8) PRIMARY KEY,
	MAKH VARCHAR(8),
	NGAYLAP DATE,
	TONGTIEN MONEY,
	CONSTRAINT FK_HD_KH FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH)
)
GO
CREATE TABLE SANPHAM (
	MASP VARCHAR(8) PRIMARY KEY,
	TENSP NVARCHAR(50),
	SOLUONGTON INT, 
	MOTA NVARCHAR(100),
	GIA MONEY
)
GO
CREATE TABLE CT_HOADON (
	MAHD VARCHAR(8),
	MASP VARCHAR(8),
	SOLUONG INT,
	GIABAN MONEY,
	GIAGIAM MONEY,
	THANHTIEN MONEY,
	CONSTRAINT PK_CT_HOADON PRIMARY KEY(MAHD, MASP),
	CONSTRAINT FK_CT_HD FOREIGN KEY(MAHD) REFERENCES HOADON(MAHD),
	CONSTRAINT FK_CT_SP FOREIGN KEY(MASP) REFERENCES SANPHAM(MASP)
)
GO 