USE QuanLyHoaDon


--TRIGGER TRÊN BẢNG HOADON CHO VIEC THEM SUA
GO
CREATE TRIGGER TG_TONGTIEN_FOR_INSERT_UPDATE_HOADON
ON HOADON FOR UPDATE
AS
BEGIN
	UPDATE HOADON
	SET HOADON.TONGTIEN = (SELECT SUM(CT.THANHTIEN)
							FROM CT_HOADON CT
							WHERE CT.MAHD = HOADON.MAHD
							GROUP BY CT.MAHD
							)
	WHERE HOADON.MAHD IN (SELECT DISTINCT inserted.MAHD
							FROM inserted)
END
GO

--TRIGGER TRÊN BẢNG CT_HOADON CHO VIEC THEM SUA
CREATE TRIGGER TG_TONGTIEN_FOR_INSERT_UPDATE_CTHD
ON CT_HOADON FOR UPDATE, INSERT
AS
BEGIN
	IF EXISTS(SELECT * FROM inserted
				WHERE inserted.GIAGIAM > inserted.GIABAN)
		BEGIN
			PRINT(N'Giá giảm không được vượt quá giá bán!')
			ROLLBACK
		END
	UPDATE CT_HOADON
	SET THANHTIEN = inserted.SOLUONG * (inserted.GIABAN - inserted.GIAGIAM)
	FROM CT_HOADON
	JOIN inserted ON inserted.MAHD = CT_HOADON.MAHD AND inserted.MASP = CT_HOADON.MASP
	
	-- Gọi trigger update tổng tiền trên bảng HOADON
	UPDATE HOADON
	SET HOADON.TONGTIEN = 0 
	WHERE HOADON.MAHD IN (SELECT DISTINCT inserted.MAHD
							FROM inserted)
END

GO
--TRIGGER TRÊN BẢNG CT_HOADON CHO VIEC XOA
CREATE TRIGGER TG_TONGTIEN_FOR_DELETE_CTHD
ON CT_HOADON FOR DELETE
AS
BEGIN
	UPDATE HOADON
	SET HOADON.TONGTIEN -= (SELECT SUM(deleted.THANHTIEN)
							FROM deleted
							WHERE HOADON.MAHD = deleted.MAHD
							GROUP BY deleted.MAHD
							)
	WHERE HOADON.MAHD IN (SELECT DISTINCT MAHD
						FROM deleted)
END


--------------------------------------------------------------------------------------------------------


