USE QuanLyHoaDon
GO

-- e. Danh sách sản phẩm bán chạy nhất.
SELECT * 
FROM SANPHAM AS SP
WHERE SP.MASP IN (SELECT MASP
				FROM CT_HOADON
				GROUP BY MASP
				HAVING SUM(SOLUONG) >= ALL(
							SELECT SUM(CT.SOLUONG)
							FROM CT_HOADON AS CT
							GROUP BY MASP
							) 
				)


GO

-- f. Sản phẩm có doanh thu cao nhất.
SELECT * 
FROM SANPHAM AS SP
WHERE SP.MASP IN ( SELECT MASP
				FROM CT_HOADON
				GROUP BY MASP
				HAVING SUM(THANHTIEN) >= ALL(
							SELECT SUM(CT.THANHTIEN)
							FROM CT_HOADON AS CT
							GROUP BY MASP
							) 
				)
