USE QuanLyHoaDon


--TRIGGER TRÊN BẢNG HOADON CHO VIEC THEM SUA
GO
CREATE TRIGGER TG_TONGTIEN_FOR_INSERT_UPDATE_HOADON
ON HOADON FOR INSERT, UPDATE
AS
BEGIN
	UPDATE HOADON
	SET TONGTIEN = (SELECT SUM(CT_HOADON.THANHTIEN)
					FROM CT_HOADON JOIN inserted ON (CT_HOADON.MAHD=inserted.MAHD)
					WHERE inserted.MAHD = HOADON.MAHD)
END
----

--TRIGGER TRÊN BẢNG CT_HOADON CHO VIEC THEM SUA
GO
CREATE TRIGGER TG_TONGTIEN_FOR_INSERT_UPDATE_CTHD
ON CT_HOADON FOR INSERT, UPDATE
AS
BEGIN
	DECLARE @SUM MONEY = 0

	SELECT @SUM = (SELECT SUM(inserted.THANHTIEN) 
	FROM inserted JOIN HOADON HD ON (inserted.MAHD=HD.MAHD))

	UPDATE HOADON
	SET HOADON.TONGTIEN = @SUM
	WHERE HOADON.MAHD = MAHD
END


--XOA 
GO
CREATE TRIGGER TG_TONGTIEN_FOR_DELETE_CTHD
ON CT_HOADON FOR DELETE
AS
BEGIN
	DECLARE @SUM MONEY = 0

	SELECT @SUM = (SELECT SUM(deleted.THANHTIEN) 
	FROM deleted JOIN HOADON HD ON (deleted.MAHD=HD.MAHD))

	UPDATE HOADON
	SET HOADON.TONGTIEN = @SUM
	WHERE HOADON.MAHD = MAHD
END
