-- Sau khi khởi tạo data từ dbForge -> dùng script này để cập nhật lại 1 số data.

USE QuanLyHoaDon
GO

UPDATE KHACHHANG SET TPHO = N'TP. Hồ Chí Minh' WHERE TPHO IS NULL

UPDATE SANPHAM SET MOTA = N'Mô tả ' + TENSP WHERE MOTA IS NOT NULL

UPDATE CT_HOADON SET THANHTIEN = SOLUONG * (GIABAN - GIAGIAM)

UPDATE HOADON SET TONGTIEN = (SELECT SUM(THANHTIEN)
							FROM CT_HOADON
							WHERE HOADON.MAHD = CT_HOADON.MAHD
							GROUP BY CT_HOADON.MAHD)

